name: nvim-metals ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Setup luacheck
      run: |
        sudo apt update &&
        sudo apt install -y lua5.1 luarocks &&
        sudo luarocks install luacheck

    - name: Run luacheck
      run: |
        luacheck .
